resources:
- manager.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: pravega/bookkeeper-operator
  newName: testbkop/bookkeeper-operator-testimages
  newTag: 0.1.8-94-671d745
