apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "arkid.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "arkid.name" . }}
    helm.sh/chart: {{ include "arkid.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "arkid.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "arkid.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      initContainers:
      - image: busybox
        command:
        - sh
        - -c
        - echo 65535 > /proc/sys/net/core/somaxconn
        imagePullPolicy: Always
        name: setsysctl
        securityContext:
          privileged: true
      containers:
        - name: "{{ .Chart.Name }}-{{ .Values.image.webServer.name }}"
          image: "{{ .Values.image.webServer.repository }}:{{ .Values.image.webServer.tag }}"
          imagePullPolicy: {{ .Values.image.webServer.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /ping/
              port: http
          readinessProbe:
            httpGet:
              path: /ping/
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: "settings-local"
              mountPath: "/var/oneid/settings_local.py"
              subPath: "settings_local.py"
            - name: arkid-data
              mountPath: /var/oneid/upload
              subPath: be/upload
            # @TODO: mount plugins
            # - name: arkid-data
            #   mountPath: /var/oneid/plugins
            #   subPath: be/plugins

        - name: "{{ .Chart.Name }}-{{ .Values.image.webServerBroker.name }}"
          image: "{{ .Values.image.webServerBroker.repository }}:{{ .Values.image.webServerBroker.tag }}"
          imagePullPolicy: {{ .Values.image.webServerBroker.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          args: ["broker", "-t", "http://localhost", "-p", "8080"]

        - name: "{{ .Chart.Name }}-{{ .Values.image.redis.name }}"
          image: "{{ .Values.image.redis.repository }}:{{ .Values.image.redis.tag }}"
          imagePullPolicy: {{ .Values.image.redis.pullPolicy }}

        - name: "{{ .Chart.Name }}-{{ .Values.image.mysqlDatabase.name }}"
          image: "{{ .Values.image.mysqlDatabase.repository}}:{{ .Values.image.mysqlDatabase.tag }}"
          imagePullPolicy: {{ .Values.image.mysqlDatabase.pullPolicy }}
          args:
            - "--character-set-server=utf8mb4"
            - "--collation-server=utf8mb4_unicode_ci"

          {{- if .Values.persistence.init }}
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: {{ .Values.persistence.mysql.rootPassword}}
            - name: MYSQL_DATABASE
              value: {{ .Values.persistence.mysql.database}}
          {{ end }}
          volumeMounts:
            - name: arkid-data
              mountPath: /var/lib/mysql
              subPath: mysql/data
            - name: arkid-data
              mountPath: /etc/mysql/conf.d
              subPath: mysql/config

        - name: "{{ .Chart.Name }}-{{ .Values.image.ldap.name }}"
          image: "{{ .Values.image.ldap.repository }}:{{ .Values.image.ldap.tag }}"
          imagePullPolicy: {{ .Values.image.ldap.pullPolicy }}
          env:
          - name: SQL_HOST
            value: "127.0.0.1"
          - name: SQL_PORT
            value: "3306"
          - name: SQL_USER
            value: "root"
          - name: SQL_PWD
            value: "{{ .Values.persistence.mysql.rootPassword}}"
          - name: LDAP_PASSWORD
            value: "{{ .Values.ldap.adminPassword }}"
          - name: SQL_DB
            value: "{{ .Values.persistence.mysql.database}}"
          - name: BACKEND
            value: "sql"

      volumes:
        - name: settings-local
          configMap:
            name: {{ template "arkid.fullname" . }}
        - name: arkid-data
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.claimName }}

      {{if .Values.imagePullSecrets }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets }}
      {{- end }}
