{{- if .Values.ingress.enabled -}}
{{- $fullName := include "arkid.fullname" . -}}
{{- $ingressPaths := .Values.ingress.paths -}}
{{- $domain := .Values.ingress.host.name -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app.kubernetes.io/name: {{ include "arkid.name" . }}
    helm.sh/chart: {{ include "arkid.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
    - hosts:
      - {{ $domain }}
      secretName: {{ .Release.Name }}-crt
{{- end }}
  rules:
    - host: {{ $domain }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ $fullName }}-portal
              servicePort: {{ .Values.service.portal.port }}
{{- end }}
