apiVersion: v1
kind: Service
metadata:
  name: "{{ include "arkid.fullname" . }}-fe"
  labels:
    app.kubernetes.io/name: "{{ include "arkid.name" . }}-fe"
    helm.sh/chart: {{ include "arkid.chart" . }}
    app.kubernetes.io/instance: "{{ .Release.Name }}-fe"
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.feServer.port}}
      targetPort: http
      protocol: TCP
      name: http

  selector:
    app.kubernetes.io/name: "{{ include "arkid.name" . }}-fe"
    app.kubernetes.io/instance: "{{ .Release.Name }}-fe"
