apiVersion: v1
kind: Service
metadata:
  name: {{ include "arkid.fullname" . }}-ldap
  labels:
    app.kubernetes.io/name: {{ include "arkid.name" . }}-ldap
    helm.sh/chart: {{ include "arkid.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}-ldap
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.ldapService.type }}
  ports:
    - name: ldap
      port: {{ .Values.ldapService.ldap.port }}
      {{- if .Values.ldapService.ldap.nodePort }}
      nodePort: {{ .Values.ldapService.ldap.nodePort }}
      {{- end }}
      targetPort: 389
      protocol: TCP
    - name: ldaps
      port:  {{ .Values.ldapService.ldaps.port }}
      {{- if .Values.ldapService.ldaps.nodePort }}
      nodePort: {{ .Values.ldapService.ldaps.nodePort }}
      {{- end }}
      targetPort: 636
      protocol: TCP

  selector:
    app.kubernetes.io/name: {{ include "arkid.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
