apiVersion: v1
kind: Service
metadata:
  name: "{{ include "arkid.fullname" . }}-portal"
  labels:
    app.kubernetes.io/name: "{{ include "arkid.name" . }}-portal"
    helm.sh/chart: {{ include "arkid.chart" . }}
    app.kubernetes.io/instance: "{{ .Release.Name }}-portal"
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.portal.port}}
      targetPort: 80
      protocol: TCP
      name: http

  selector:
    app.kubernetes.io/name: "{{ include "arkid.name" . }}-portal"
    app.kubernetes.io/instance: "{{ .Release.Name }}-portal"
