apiVersion: v1
kind: ServiceAccount
metadata:
  name: bookkeeper-operator

---  

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: bookkeeper-operator
rules:
- apiGroups:
  - bookkeeper.pravega.io
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - "*"
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - "*"
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - '*'

---


kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: bookkeeper-operator
subjects:
- kind: ServiceAccount
  name: bookkeeper-operator
roleRef:
  kind: Role
  name: bookkeeper-operator
  apiGroup: rbac.authorization.k8s.io

---

