
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - bookkeeper.pravega.io
  resources:
  - bookkeeperclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bookkeeper.pravega.io
  resources:
  - bookkeeperclusters/finalizers
  verbs:
  - update
- apiGroups:
  - bookkeeper.pravega.io
  resources:
  - bookkeeperclusters/status
  verbs:
  - get
  - patch
  - update
